### ISSUE TITLE
Separate \everymplib and \everyendmplib for different instances

### ISSUE THREAD

**Issue by jemmybutton** [lualatex/luamplib#102]
Currently global `\everymplib` and `\everyendmplib` are used with MetaPost code in all MetaPost instances. However, it is desirable to be able to have separate `\everymplib` and `\everyendmplib` for each MetaPost instance. At first glance, syntax like this, with an optional argument for instance name, like [in the LaTeX environment](https://github.com/lualatex/luamplib/pull/100), seems appropriate:
```
\everymplib[instanceName]{...}
\everyendmplib[instanceName]{...}
```
However, the implementation of `\everymplib` and `\everyendmplib` unlike that of the LaTeX `mplibcode` environment, employs plain TeX `\def` which makes it more difficult to add an optional argument. So it may make sense to keep plain TeX code intact and add multiple instance support in `\everymplib` and `\everyendmplib` for LaTeX separately somehow.

**Comment by dohyunkim** [comment]
I'm wondering whether #103 is a solution to your issue. Please let me know. 
When it turns out to be usable, then a new version will be released.

**Comment by dohyunkim** [comment]
Yes. That seems to be reasonable.
Just committed #104.

**Comment by jemmybutton** [comment]
Thank you so much!
