### ISSUE TITLE
Package luamplib Warning: take dvipdfmx path, no support for other dvi tools currently. 

### ISSUE THREAD

**Issue by Reissner** [lualatex/luamplib#115]
In your documentation I read: 

In the past, the package required PDF mode in order to output something. Starting
with version 2.7 it works in DVI mode as well, though DVIPDFMx is the only DVI tool
currently supported. 

When compiling with `lualatex -output-format=dvi`, 
a warning is logged: 

```
Package luamplib Warning: take dvipdfmx path, no support for other dvi tools currently. 
```

A warning means, something may not be ideal. 
Is this the case here? 
What shall I do to fix? 

I suspect, there is no degradation so it should be an info: 

```
Package luamplib Info: take dvipdfmx path, no support for other dvi tools currently. 
```

Please take for serious, because I have a quality assurance system warning me about things like these.

**Comment by dohyunkim** [comment]
Thanks for the report.
Just uploaded to ctan a new version.
