### ISSUE TITLE
'outlinetext' feature

### ISSUE THREAD

**Issue by jemmybutton** [lualatex/luamplib#133]
There's `outlinetext` function in ConTeXt's font loading system, which is sometimes very useful, and which, at the moment, seems to be missing in LuaLaTeX's set of MetaPost tools. In ConTeXt it's a part of font loading system. For this reason I though it might be a feature of `luaotfload` https://github.com/latex3/luaotfload/issues/271 to make things more similar. 
With `mplibglyph` function https://github.com/lualatex/luamplib/pull/132 `luamplib` seems to be closer to the implementation of `outlinetext` than `luaotfload` and more logical at that.

**Comment by dohyunkim** [comment]
v2.31 provides a new metapost operator `mpliboutlinetext`. Please give it a try.

**Comment by jemmybutton** [comment]
This works absolutely fantastic! Thank you so much! In fact, it seems to work even better than the original `outlinetext` in some respects. For instance, it seems to respect RtL scripts, which `outlinetext` had troubles with ( https://tracker.luatex.org/view.php?id=1023 ) and, as of now, as I just tested, still has.

**Comment by jemmybutton** [comment]
Oh, sorry, the issue can be closed
