### ISSUE TITLE
luamplib doesn't work with new LuaTeX version

### ISSUE THREAD

**Issue by franckpastor** [lualatex/luamplib#66]
Hello,

Since LuaTeX 1.00, luamplib doesn't work directly. It seems that luamplib calls some pdfTeX primitives that are not recognized any more by this new version of LuaTeX. The recommended workaround is to load the luatex85 package to enable the use of these primitives. It works then fine, but is there a project to make luamplib work with this version of LuaTeX (and the following ones) directly, without any workaround package needed?

Thanks, and happy new year!

Franck Pastor

**Comment by franckpastor** [comment]
Update: I found that luamplib had nothing to do with this problem. The culprit is the `standalone` class that I use for a good deal of my pictures. Probably because `standalone` needs the PDF primitives that the most recent versions of LuaTeX does not recognize any more.

**Comment by davidcarlisle** [comment]
Martin has been updating his packages over the last week or so so most likely this will get fixed, but for packages that are not updated you can use the luatex85 package at the start of the document that defines all the old pdftex names for compatibility.

**Comment by franckpastor** [comment]
In the meantime, fortunately, I had already learned about this `luatex85` package. But it is good to know that we will be able to combine `luamplib` and `standalone` without having to load this. Thanks!
