### ISSUE TITLE
Code accessing global variable 't'

### ISSUE THREAD

**Issue by z-rui** [lualatex/luamplib#76]
The following call passes 3 arguments to `flushnormalpath` while the function only takes 2 arguments:
https://github.com/lualatex/luamplib/blob/4227cb131ef94c9f914142c28201a3c42e7bb6ba/luamplib.dtx#L1565

The last statement in `flush{normal,concat}path` also refers to this non-existent variable:
https://github.com/lualatex/luamplib/blob/4227cb131ef94c9f914142c28201a3c42e7bb6ba/luamplib.dtx#L941
https://github.com/lualatex/luamplib/blob/4227cb131ef94c9f914142c28201a3c42e7bb6ba/luamplib.dtx#L974

Are they possible bugs?

**Comment by dohyunkim** [comment]
All you pointed out seem to be bugs.
I will fix them when next update becomes needy.
Thanks for the report.
