### ISSUE TITLE
Latex command inside metapost label

### ISSUE THREAD

**Issue by mb4e** [lualatex/luamplib#86]
Hello, this is a minimal code example, compiling with lualatex 1.10.0.

```
\documentclass[12pt]{article}
\usepackage{luamplib}
\begin{document}
\begin{mplibcode}
beginfig(1)
label(btex A-\textbf{B} etex,origin);
endfig;
\end{mplibcode}
\end{document}
```
Link : https://tex.stackexchange.com/q/516247/56520

**Comment by dohyunkim** [comment]
Just uploaded a patch and sent to ctan a new release, which is expected to reach texlive in a few days. 
(Anyway I have to investigate what is the real cause of the issue when I have time.)
